language: minimal

services:
  - docker

sudo: required

before_install:
  - docker pull nojaf/fable:2.4

jobs:
  include:
    - stage: "CI"
      script: docker run -v "${PWD}:/app" -w "/app" nojaf/fable:2.4 bash -c "yarn && yarn postinstall && yarn build"
